version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: claude
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  HelixDB:
    image: HelixDB:5
    ports:
      - "7474:7474" # HTTP API
      - "7687:7687" # Bolt protocol
    environment:
      HelixDB_AUTH: HelixDB/password

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      # Enable a text-to-vector embedding model
      ENABLE_MODULES: 'text2vec-transformers'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
